// Весь VS Code IDE в одном автономном HTML-файле.
// Склеивается из строк, чтобы обратные кавычки и кавычки внутри JS-кода
// не ломали TypeScript-парсер.

const _ = (s: string) => s;
const Q = '"';       // двойная кавычка
const q = "'";       // одинарная кавычка
const BT = '\x60';  // обратная кавычка (backtick)

// Шапка HTML
const HEAD = [
  '<!DOCTYPE html>',
  '<html lang="ru">',
  '<head>',
  '<meta charset="UTF-8"/>',
  '<meta name="viewport" content="width=device-width, initial-scale=1.0"/>',
  '<title>VS Code \u2014 standalone</title>',
  '<script src="https://cdn.tailwindcss.com"></scr'+'ipt>',
  '<script src="https://unpkg.com/react@18/umd/react.development.js"></scr'+'ipt>',
  '<script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js"></scr'+'ipt>',
  '<link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;700&family=Inter:wght@400;500;600&display=swap" rel="stylesheet"/>',
  '<style>',
  '* { box-sizing: border-box; margin: 0; padding: 0; }',
  'body { font-family: Inter,sans-serif; background:#1e1e1e; color:#cccccc; overflow:hidden; height:100vh; }',
  'textarea { font-family: "JetBrains Mono",monospace !important; }',
  '::-webkit-scrollbar { width:8px; height:8px; }',
  '::-webkit-scrollbar-track { background:#1e1e1e; }',
  '::-webkit-scrollbar-thumb { background:#424242; border-radius:4px; }',
  '::-webkit-scrollbar-thumb:hover { background:#555; }',
  '</style>',
  '</head>',
  '<body>',
  '<div id="root"></div>',
  '<script>',
].join('\n');

// Все утилиты и логика — через массив строк, без шаблонных литералов
const LOGIC: string[] = [
  _('const { useState, useRef, useMemo, useEffect, createElement: h } = React;'),
  '',
  '// VFS',
  _('let _id=0; const uid=()=>' + Q + 'n' + Q + '+Date.now()+" _"+(_id++);'),
  _('const mkFile=(name,content=' + Q + Q + ')=>({id:uid(),name,type:' + Q + 'file' + Q + ',content});'),
  _('const mkDir=(name,children=[],open=false)=>({id:uid(),name,type:' + Q + 'folder' + Q + ',children,open});'),
  _('function findNode(t,id){for(const n of t){if(n.id===id)return n;if(n.children){const f=findNode(n.children,id);if(f)return f;}}return null;}'),
  _('function removeNode(t,id){return t.filter(n=>n.id!==id).map(n=>n.children?{...n,children:removeNode(n.children,id)}:n);}'),
  _('function updateNode(t,id,p){return t.map(n=>{if(n.id===id)return{...n,...p};if(n.children)return{...n,children:updateNode(n.children,id,p)};return n;});}'),
  _('function addNode(t,pid,node){if(!pid)return[...t,node];return t.map(n=>{if(n.id===pid&&n.type==' + Q + 'folder' + Q + ')return{...n,open:true,children:[...(n.children||[]),node]};if(n.children)return{...n,children:addNode(n.children,pid,node)};return n;});}'),
  '',
  '// Подсветка синтаксиса',
  _('const C={kw:' + Q + '#c586c0' + Q + ',tp:' + Q + '#4ec9b0' + Q + ',fn:' + Q + '#dcdcaa' + Q + ',st:' + Q + '#ce9178' + Q + ',nm:' + Q + '#b5cea8' + Q + ',cm:' + Q + '#6a9955' + Q + ',op:' + Q + '#d4d4d4' + Q + ',vr:' + Q + '#9cdcfe' + Q + ',bl:' + Q + '#569cd6' + Q + ',pl:' + Q + '#d4d4d4' + Q + ',pu:' + Q + '#d4d4d4' + Q + '};'),
  _('const KW=new Set([' + Q + 'const' + Q + ',' + Q + 'let' + Q + ',' + Q + 'var' + Q + ',' + Q + 'function' + Q + ',' + Q + 'return' + Q + ',' + Q + 'if' + Q + ',' + Q + 'else' + Q + ',' + Q + 'for' + Q + ',' + Q + 'while' + Q + ',' + Q + 'class' + Q + ',' + Q + 'extends' + Q + ',' + Q + 'import' + Q + ',' + Q + 'export' + Q + ',' + Q + 'from' + Q + ',' + Q + 'default' + Q + ',' + Q + 'async' + Q + ',' + Q + 'await' + Q + ',' + Q + 'try' + Q + ',' + Q + 'catch' + Q + ',' + Q + 'new' + Q + ',' + Q + 'type' + Q + ',' + Q + 'interface' + Q + ',' + Q + 'def' + Q + ',' + Q + 'elif' + Q + ',' + Q + 'pass' + Q + ',' + Q + 'raise' + Q + ',' + Q + 'with' + Q + ',' + Q + 'as' + Q + ',' + Q + 'and' + Q + ',' + Q + 'or' + Q + ',' + Q + 'not' + Q + ',' + Q + 'is' + Q + ',' + Q + 'None' + Q + ',' + Q + 'self' + Q + ',' + Q + 'this' + Q + ',' + Q + 'static' + Q + ',' + Q + 'void' + Q + ',' + Q + 'typeof' + Q + ',' + Q + 'delete' + Q + ',' + Q + 'in' + Q + ',' + Q + 'of' + Q + ',' + Q + 'switch' + Q + ',' + Q + 'case' + Q + ',' + Q + 'break' + Q + ',' + Q + 'continue' + Q + ',' + Q + 'throw' + Q + ',' + Q + 'finally' + Q + ',' + Q + 'yield' + Q + ',' + Q + 'do' + Q + ',' + Q + 'instanceof' + Q + ',' + Q + 'public' + Q + ',' + Q + 'private' + Q + ',' + Q + 'protected' + Q + ']);'),
  _('const TYPES=new Set([' + Q + 'string' + Q + ',' + Q + 'number' + Q + ',' + Q + 'boolean' + Q + ',' + Q + 'any' + Q + ',' + Q + 'never' + Q + ',' + Q + 'unknown' + Q + ',' + Q + 'int' + Q + ',' + Q + 'float' + Q + ',' + Q + 'bool' + Q + ',' + Q + 'str' + Q + ',' + Q + 'Array' + Q + ',' + Q + 'Object' + Q + ',' + Q + 'Promise' + Q + ',' + Q + 'Map' + Q + ',' + Q + 'Set' + Q + ',' + Q + 'React' + Q + ',' + Q + 'Date' + Q + ',' + Q + 'Math' + Q + ',' + Q + 'JSON' + Q + ',' + Q + 'console' + Q + ']);'),
  _('const BOOLS=new Set([' + Q + 'true' + Q + ',' + Q + 'false' + Q + ',' + Q + 'null' + Q + ',' + Q + 'undefined' + Q + ',' + Q + 'True' + Q + ',' + Q + 'False' + Q + ',' + Q + 'nil' + Q + ']);'),
  _('function isQ(c){var d=String.fromCharCode(34),s=String.fromCharCode(39);return c===d||c===s;}'),
  _('function tokenCode(line){var tk=[],i=0,n=line.length;while(i<n){var c=line[i];if(c===" "){var j=i;while(j<n&&line[j]===" ")j++;tk.push({t:line.slice(i,j),c:C.pl});i=j;continue;}if(c==="/"&&line[i+1]==="/"){tk.push({t:line.slice(i),c:C.cm});break;}if(c==="#"){tk.push({t:line.slice(i),c:C.cm});break;}if(isQ(c)){var q2=c,j2=i+1;while(j2<n&&line[j2]!==q2){if(line[j2]==="\\\\")j2++;j2++;}j2=Math.min(j2+1,n);tk.push({t:line.slice(i,j2),c:C.st});i=j2;continue;}if(/[0-9]/.test(c)){var j3=i;while(j3<n&&/[0-9a-fx._]/i.test(line[j3]))j3++;tk.push({t:line.slice(i,j3),c:C.nm});i=j3;continue;}if(/[a-zA-Z_$]/.test(c)){var j4=i;while(j4<n&&/[a-zA-Z0-9_$]/.test(line[j4]))j4++;var w=line.slice(i,j4),af=j4;while(af<n&&line[af]===" ")af++;var cl=C.vr;if(KW.has(w))cl=C.kw;else if(BOOLS.has(w))cl=C.bl;else if(TYPES.has(w))cl=C.tp;else if(line[af]==="(")cl=C.fn;else if(/^[A-Z]/.test(w))cl=C.tp;tk.push({t:w,c:cl});i=j4;continue;}if(/[{}()[\\];,.]/.test(c)){tk.push({t:c,c:C.pu});i++;continue;}if(/[+\\-*/%=<>!&|^~?:]/.test(c)){tk.push({t:c,c:C.op});i++;continue;}tk.push({t:c,c:C.pl});i++;}return tk;}'),
  _('function detectLang(name){var e=(name.split(' + Q + '.' + Q + ').pop()||' + Q + Q + ').toLowerCase();return {ts:' + Q + 'typescript' + Q + ',tsx:' + Q + 'typescript' + Q + ',js:' + Q + 'javascript' + Q + ',jsx:' + Q + 'javascript' + Q + ',py:' + Q + 'python' + Q + ',json:' + Q + 'json' + Q + ',html:' + Q + 'html' + Q + ',css:' + Q + 'css' + Q + ',md:' + Q + 'markdown' + Q + '}[e]||' + Q + 'text' + Q + ';}'),
  _('function fileEmoji(name){var e=(name.split(' + Q + '.' + Q + ').pop()||' + Q + Q + ').toLowerCase();return{tsx:' + Q + '\ud83d\udd37' + Q + ',ts:' + Q + '\ud83d\udd37' + Q + ',jsx:' + Q + '\ud83d\udfe8' + Q + ',js:' + Q + '\ud83d\udfe8' + Q + ',py:' + Q + '\ud83d\udc0d' + Q + ',json:' + Q + '\ud83d\udccb' + Q + ',html:' + Q + '\ud83c\udf10' + Q + ',css:' + Q + '\ud83c\udfa8' + Q + ',md:' + Q + '\ud83d\udcdd' + Q + '}[e]||' + Q + '\ud83d\udcc4' + Q + ';}'),
  _('function tokenLine(line,lang){if(!line)return[{t:' + Q + Q + ',c:C.pl}];if(lang===' + Q + 'markdown' + Q + ')return[{t:line,c:C.pl}];return tokenCode(line);}'),
  '',
  '// Начальное дерево файлов',
  'var INIT_TREE = [',
  '  mkDir(' + Q + 'src' + Q + ', [',
  '    mkDir(' + Q + 'components' + Q + ', [',
  '      mkFile(' + Q + 'Button.jsx' + Q + ', ' + Q + 'export function Button({label,onClick}){\\n  return <button onClick={onClick}>{label}</button>;\\n}\\n' + Q + '),',
  '    ], true),',
  '    mkFile(' + Q + 'App.jsx' + Q + ', ' + Q + 'import React,{useState} from "react";\\nfunction App(){\\n  const[count,setCount]=useState(0);\\n  return <div><h1>VS Code Clone</h1><p>Clicks: {count}</p></div>;\\n}\\nexport default App;\\n' + Q + '),',
  '    mkFile(' + Q + 'index.css' + Q + ', ' + Q + ':root{\\n  --primary:#007acc;\\n}\\nbody{background:#1e1e1e;color:#ccc;padding:24px;}\\n' + Q + '),',
  '  ], true),',
  '  mkFile(' + Q + 'package.json' + Q + ', ' + Q + '{\\n  "name": "my-app",\\n  "version": "1.0.0"\\n}\\n' + Q + '),',
  '  mkFile(' + Q + 'index.html' + Q + ', ' + Q + '<!DOCTYPE html>\\n<html>\\n<head><title>My App</title></head>\\n<body><div id="root"></div></body>\\n</html>\\n' + Q + '),',
  '  mkFile(' + Q + 'README.md' + Q + ', ' + Q + '# My Project\\n\\n## Запуск\\n\\nnpm install\\nnpm run dev\\n' + Q + '),',
  '];',
  '',
  '// Автодополнение',
  'var PAIRS = {"(":")", "{":"}", "[":"]"};',
  'var CLOSERS = new Set([")", "}", "]"]);',
  'var AC = [' + Q + 'function' + Q + ',' + Q + 'return' + Q + ',' + Q + 'const' + Q + ',' + Q + 'let' + Q + ',' + Q + 'import' + Q + ',' + Q + 'export' + Q + ',' + Q + 'default' + Q + ',' + Q + 'interface' + Q + ',' + Q + 'console' + Q + ',' + Q + 'useState' + Q + ',' + Q + 'useEffect' + Q + ',' + Q + 'className' + Q + ',' + Q + 'async' + Q + ',' + Q + 'await' + Q + '];',
  '',
  '// CodeEditor',
  'function CodeEditor({value,lang,onChange}){',
  '  var taRef=useRef(null);',
  '  var lines=value.split("\\n");',
  '  var hl=useMemo(function(){return lines.map(function(l){return tokenLine(l,lang);});},[value,lang]);',
  '  function setSel(v,pos){onChange(v);requestAnimationFrame(function(){if(taRef.current){taRef.current.selectionStart=taRef.current.selectionEnd=pos;}});}',
  '  function onKD(e){',
  '    var ta=e.target,s=ta.selectionStart,end=ta.selectionEnd,v=ta.value;',
  '    if(e.key==="Tab"){e.preventDefault();if(s===end){var m=v.slice(0,s).match(/([a-zA-Z_$]+)$/);if(m){var found=AC.find(function(k){return k.toLowerCase().startsWith(m[1].toLowerCase())&&k.length>m[1].length;});if(found){var ins=found.slice(m[1].length);setSel(v.slice(0,s)+ins+v.slice(end),s+ins.length);return;}}}setSel(v.slice(0,s)+"  "+v.slice(end),s+2);return;}',
  '    if(PAIRS[e.key]&&s===end){e.preventDefault();setSel(v.slice(0,s)+e.key+PAIRS[e.key]+v.slice(end),s+1);return;}',
  '    if(CLOSERS.has(e.key)&&v[s]===e.key&&s===end){e.preventDefault();setSel(v,s+1);return;}',
  '    if(e.key==="Backspace"&&s===end&&s>0&&PAIRS[v[s-1]]===v[s]){e.preventDefault();setSel(v.slice(0,s-1)+v.slice(s+1),s-1);return;}',
  '    if(e.key==="Enter"){var ls=v.lastIndexOf("\\n",s-1)+1;var ind=(v.slice(ls,s).match(/^[ \\t]/)||[""])[0];if("([{".includes(v[s-1])){e.preventDefault();var ex=ind+"  ";if(")]}".includes(v[s]))setSel(v.slice(0,s)+"\\n"+ex+"\\n"+ind+v.slice(s),s+1+ex.length);else setSel(v.slice(0,s)+"\\n"+ex+v.slice(s),s+1+ex.length);return;}if(ind){e.preventDefault();setSel(v.slice(0,s)+"\\n"+ind+v.slice(end),s+1+ind.length);return;}}',
  '  }',
  '  var ST={display:"flex",flex:1,overflow:"auto",background:"#1e1e1e",fontSize:13.5,lineHeight:"20px"};',
  '  var LN={userSelect:"none",padding:"12px 12px 12px 16px",textAlign:"right",color:"#858585",background:"#1e1e1e",position:"sticky",left:0,zIndex:10,minWidth:52,fontFamily:"JetBrains Mono,monospace",fontSize:13.5,lineHeight:"20px"};',
  '  return h("div",{style:ST},',
  '    h("div",{style:LN},lines.map(function(_,i){return h("div",{key:i,style:{height:20}},i+1);})),',
  '    h("div",{style:{position:"relative",flex:1,padding:"12px 24px 12px 0"}},',
  '      h("div",{"aria-hidden":"true",style:{position:"absolute",inset:0,padding:"12px 24px 12px 0",whiteSpace:"pre",fontFamily:"JetBrains Mono,monospace",fontSize:13.5,lineHeight:"20px",pointerEvents:"none"}},',
  '        hl.map(function(toks,i){return h("div",{key:i,style:{height:20}},toks.map(function(t,j){return h("span",{key:j,style:{color:t.c}},t.t||"\\u200b");}));})),',
  '      h("textarea",{ref:taRef,value:value,onChange:function(e){onChange(e.target.value);},onKeyDown:onKD,spellCheck:false,wrap:"off",style:{position:"relative",zIndex:10,width:"100%",resize:"none",background:"transparent",color:"transparent",caretColor:"#fff",outline:"none",whiteSpace:"pre",overflow:"hidden",fontFamily:"JetBrains Mono,monospace",fontSize:13.5,lineHeight:"20px",height:lines.length*20,minHeight:"100%",border:"none",padding:0}})',
  '    )',
  '  );',
  '}',
  '',
  '// FileTree',
  'function FileTree(props){',
  '  var nodes=props.nodes,activeId=props.activeId,depth=props.depth||0,onOpen=props.onOpen,onToggle=props.onToggle,onRename=props.onRename,onDelete=props.onDelete,onCreate=props.onCreate,renamingId=props.renamingId,setRenamingId=props.setRenamingId;',
  '  var menuState=useState(null),menu=menuState[0],setMenu=menuState[1];',
  '  var sorted=[...nodes].sort(function(a,b){if(a.type!==b.type)return a.type==="folder"?-1:1;return a.name.localeCompare(b.name);});',
  '  return h("div",{onClick:function(){if(menu)setMenu(null);}},',
  '    sorted.map(function(node){return h("div",{key:node.id},',
  '      h("div",{',
  '        onClick:function(){if(node.type==="folder")onToggle(node.id);else onOpen(node);},',
  '        onContextMenu:function(e){e.preventDefault();setMenu({id:node.id,type:node.type,x:e.clientX,y:e.clientY});},',
  '        style:{display:"flex",alignItems:"center",gap:4,paddingLeft:8+depth*14,paddingRight:8,paddingTop:2,paddingBottom:2,cursor:"pointer",fontSize:13,background:activeId===node.id?"#37373d":"transparent"},',
  '        onMouseEnter:function(e){if(activeId!==node.id)e.currentTarget.style.background="#2a2d2e";},',
  '        onMouseLeave:function(e){if(activeId!==node.id)e.currentTarget.style.background="transparent";}},',
  '        node.type==="folder"?h("span",{style:{fontSize:10,color:"#858585",width:12,display:"inline-block"}},node.open?"\\u25bc":"\\u25b6"):h("span",{style:{width:12,display:"inline-block"}}),',
  '        h("span",{style:{marginRight:4}},node.type==="folder"?(node.open?"\\ud83d\\udcc2":"\\ud83d\\udcc1"):fileEmoji(node.name)),',
  '        renamingId===node.id',
  '          ?h("input",{autoFocus:true,defaultValue:node.name,style:{flex:1,background:"#3c3c3c",border:"1px solid #007acc",color:"#ccc",padding:"0 4px",outline:"none",fontSize:13},',
  '              onClick:function(e){e.stopPropagation();},',
  '              onBlur:function(e){onRename(node.id,e.target.value.trim()||node.name);setRenamingId(null);},',
  '              onKeyDown:function(e){if(e.key==="Enter"){onRename(node.id,e.target.value.trim()||node.name);setRenamingId(null);}if(e.key==="Escape")setRenamingId(null);}})',
  '          :h("span",{style:{flex:1,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}},node.name)',
  '      ),',
  '      node.type==="folder"&&node.open&&node.children&&h(FileTree,Object.assign({},props,{nodes:node.children,depth:depth+1}))',
  '    );}),',
  '    menu&&h("div",{style:{position:"fixed",left:menu.x,top:menu.y,background:"#252526",border:"1px solid #454545",borderRadius:4,padding:"4px 0",zIndex:1000,minWidth:180,boxShadow:"0 8px 32px rgba(0,0,0,0.6)",fontSize:13},onClick:function(e){e.stopPropagation();}},',
  '      menu.type==="folder"&&[',
  '        h("button",{key:"nf",onClick:function(){onCreate(menu.id,"file");setMenu(null);},style:{display:"flex",width:"100%",alignItems:"center",gap:8,padding:"6px 12px",background:"none",border:"none",color:"#ccc",cursor:"pointer"},onMouseEnter:function(e){e.target.style.background="#04395e";},onMouseLeave:function(e){e.target.style.background="none";}},"\\ud83d\\udcc4 New File"),',
  '        h("button",{key:"nd",onClick:function(){onCreate(menu.id,"folder");setMenu(null);},style:{display:"flex",width:"100%",alignItems:"center",gap:8,padding:"6px 12px",background:"none",border:"none",color:"#ccc",cursor:"pointer"},onMouseEnter:function(e){e.target.style.background="#04395e";},onMouseLeave:function(e){e.target.style.background="none";}},"\\ud83d\\udcc1 New Folder"),',
  '        h("div",{key:"sep",style:{height:1,background:"#454545",margin:"4px 0"}}),',
  '      ],',
  '      h("button",{onClick:function(){setRenamingId(menu.id);setMenu(null);},style:{display:"flex",width:"100%",alignItems:"center",gap:8,padding:"6px 12px",background:"none",border:"none",color:"#ccc",cursor:"pointer"},onMouseEnter:function(e){e.target.style.background="#04395e";},onMouseLeave:function(e){e.target.style.background="none";}},"\\u270f\\ufe0f Rename"),',
  '      h("button",{onClick:function(){onDelete(menu.id);setMenu(null);},style:{display:"flex",width:"100%",alignItems:"center",gap:8,padding:"6px 12px",background:"none",border:"none",color:"#f48771",cursor:"pointer"},onMouseEnter:function(e){e.target.style.background="#04395e";},onMouseLeave:function(e){e.target.style.background="none";}},"\\ud83d\\uddd1\\ufe0f Delete")',
  '    )',
  '  );',
  '}',
  '',
  '// Terminal',
  'function Terminal(){',
  '  var ls=useState([{t:"IDE Terminal \u2014 bash 5.2",c:"#858585"},{t:"Type help for commands.",c:"#858585"}]),lines=ls[0],setLines=ls[1];',
  '  var is=useState(""),input=is[0],setInput=is[1];',
  '  var hs=useState([]),hist=hs[0],setHist=hs[1];',
  '  var hi=useState(-1),hIdx=hi[0],setHIdx=hi[1];',
  '  var endRef=useRef(null);var inpRef=useRef(null);',
  '  useEffect(function(){if(endRef.current)endRef.current.scrollIntoView({behavior:"smooth"});},[lines]);',
  '  function run(cmd){',
  '    var out=[{t:"\\u279c  project $ "+cmd,c:"#4ec9b0"}];var tr=cmd.trim();if(!tr){setLines(function(l){return[...l,...out];});return;}',
  '    setHist(function(h){return[...h,cmd];});setHIdx(-1);',
  '    var parts=tr.split(/\\s+/),name=parts[0],args=parts.slice(1);',
  '    if(name==="help")out.push({t:"Commands: help clear echo ls npm python node date whoami",c:"#ccc"});',
  '    else if(name==="clear"){setLines([]);return;}',
  '    else if(name==="echo")out.push({t:args.join(" "),c:"#ccc"});',
  '    else if(name==="ls")out.push({t:"src/  package.json  index.html  README.md",c:"#ccc"});',
  '    else if(name==="npm"&&args[0]==="run"&&args[1]==="dev"){out.push({t:"VITE v5.0  ready in 312ms",c:"#ccc"});out.push({t:"\\u279c  Local: http://localhost:5173/",c:"#ccc"});}',
  '    else if(name==="npm"&&(args[0]==="install"||args[0]==="i"))out.push({t:"added 214 packages in 3s",c:"#ccc"});',
  '    else if(name==="python"||name==="python3")out.push({t:"Python 3.11.4 \u2014 ok",c:"#ccc"});',
  '    else if(name==="node")out.push({t:"v20.10.0",c:"#ccc"});',
  '    else if(name==="date")out.push({t:new Date().toString(),c:"#ccc"});',
  '    else if(name==="whoami")out.push({t:"developer",c:"#ccc"});',
  '    else out.push({t:"command not found: "+name,c:"#f48771"});',
  '    setLines(function(l){return[...l,...out];});',
  '  }',
  '  return h("div",{style:{display:"flex",flexDirection:"column",height:"100%",background:"#181818",fontFamily:"JetBrains Mono,monospace",fontSize:12.5,lineHeight:"18px"},onClick:function(){if(inpRef.current)inpRef.current.focus();}},',
  '    h("div",{style:{flex:1,overflowY:"auto",padding:"8px 12px"}},',
  '      lines.map(function(l,i){return h("div",{key:i,style:{color:l.c,whiteSpace:"pre-wrap"}},l.t);}),',
  '      h("div",{style:{display:"flex",alignItems:"center"}},',
  '        h("span",{style:{color:"#4ec9b0",marginRight:8}},"\\u279c  project $"),',
  '        h("input",{ref:inpRef,value:input,onChange:function(e){setInput(e.target.value);},',
  '          onKeyDown:function(e){',
  '            if(e.key==="Enter"){run(input);setInput("");}',
  '            else if(e.key==="ArrowUp"){e.preventDefault();var i=hIdx<0?hist.length-1:Math.max(0,hIdx-1);if(hist[i]!==undefined){setInput(hist[i]);setHIdx(i);}}',
  '            else if(e.key==="ArrowDown"){e.preventDefault();var i=hIdx+1;if(i>=hist.length){setInput("");setHIdx(-1);}else{setInput(hist[i]);setHIdx(i);}}',
  '          },',
  '          autoFocus:true,style:{flex:1,background:"transparent",border:"none",outline:"none",color:"#ccc",fontFamily:"JetBrains Mono,monospace",fontSize:12.5}})',
  '      ),',
  '      h("div",{ref:endRef})',
  '    )',
  '  );',
  '}',
  '',
  '// IDE — главный компонент',
  'function IDE(){',
  '  var ts=useState(INIT_TREE),tree=ts[0],setTree=ts[1];',
  '  var tb=useState([]),tabs=tb[0],setTabs=tb[1];',
  '  var ai=useState(null),activeId=ai[0],setActiveId=ai[1];',
  '  var ps=useState("files"),panel=ps[0],setPanel=ps[1];',
  '  var st=useState(true),showTerm=st[0],setShowTerm=st[1];',
  '  var ds=useState(new Set()),dirty=ds[0],setDirty=ds[1];',
  '  var rs=useState(null),renamingId=rs[0],setRenaming=rs[1];',
  '  var sq=useState(""),searchQ=sq[0],setSearchQ=sq[1];',
  '  var rq=useState(""),replaceQ=rq[0],setReplaceQ=rq[1];',
  '  var is=useState(new Set(["Prettier","ESLint"])),inst=is[0],setInst=is[1];',
  '  var activeNode=activeId?findNode(tree,activeId):null;',
  '  var lang=activeNode?detectLang(activeNode.name):"text";',
  '  function openFile(node){if(node.type!=="file")return;setActiveId(node.id);setTabs(function(t){return t.some(function(x){return x.id===node.id;})?t:[...t,{id:node.id,name:node.name}];});}',
  '  function closeTab(id,e){if(e)e.stopPropagation();setTabs(function(t){var nx=t.filter(function(x){return x.id!==id;});if(activeId===id)setActiveId(nx.length?nx[nx.length-1].id:null);return nx;});setDirty(function(d){var n=new Set(d);n.delete(id);return n;});}',
  '  function setContent(v){if(!activeId)return;setTree(function(t){return updateNode(t,activeId,{content:v});});setDirty(function(d){return new Set(d).add(activeId);});}',
  '  function save(){if(!activeId)return;setDirty(function(d){var n=new Set(d);n.delete(activeId);return n;});}',
  '  function toggleFolder(id){var n=findNode(tree,id);if(n)setTree(function(t){return updateNode(t,id,{open:!n.open});});}',
  '  function rename(id,name){setTree(function(t){return updateNode(t,id,{name:name});});setTabs(function(tb){return tb.map(function(x){return x.id===id?{...x,name:name}:x;});});}',
  '  function del(id){setTree(function(t){return removeNode(t,id);});closeTab(id);}',
  '  function create(pid,type){var name=type==="file"?"new-file.ts":"new-folder";var node=type==="file"?mkFile(name):mkDir(name,[],true);setTree(function(t){return addNode(t,pid,node);});if(type==="file")openFile(node);setRenaming(node.id);}',
  '  function createRoot(type){var name=type==="file"?"new-file.ts":"new-folder";var node=type==="file"?mkFile(name):mkDir(name,[],true);setTree(function(t){return[...t,node];});if(type==="file")openFile(node);setRenaming(node.id);}',
  '  var searchResults=useMemo(function(){if(!searchQ)return[];var res=[];function walk(nodes){for(var n of nodes){if(n.type==="file"&&n.content)n.content.split("\\n").forEach(function(line,i){if(line.toLowerCase().includes(searchQ.toLowerCase()))res.push({node:n,line:i+1,text:line.trim()});});if(n.children)walk(n.children);}}walk(tree);return res;},[searchQ,tree]);',
  '  function replaceAll(){if(!searchQ)return;function walk(nodes){return nodes.map(function(n){var u=n;if(n.type==="file"&&n.content&&n.content.includes(searchQ))u={...n,content:n.content.split(searchQ).join(replaceQ)};if(u.children)u={...u,children:walk(u.children)};return u;});}setTree(function(t){return walk(t);});}',
  '  function toggleExt(name){setInst(function(s){var n=new Set(s);if(n.has(name))n.delete(name);else n.add(name);return n;});}',
  '  var EXT=[{name:"Prettier",desc:"Code formatting"},{name:"ESLint",desc:"JS linter"},{name:"GitLens",desc:"Git superpowers"},{name:"Python",desc:"Python support"},{name:"Live Server",desc:"Local server"}];',
  '',
  '  return h("div",{style:{display:"flex",flexDirection:"column",height:"100vh",overflow:"hidden",background:"#1e1e1e",color:"#cccccc",userSelect:"none"}},',
  '',
  '    h("div",{style:{display:"flex",alignItems:"center",justifyContent:"space-between",height:32,background:"#3c3c3c",padding:"0 12px",fontSize:12,flexShrink:0}},',
  '      h("div",{style:{display:"flex",alignItems:"center",gap:8}},',
  '        h("div",{style:{display:"flex",gap:6}},',
  '          h("div",{style:{width:12,height:12,borderRadius:"50%",background:"#ff5f57"}}),',
  '          h("div",{style:{width:12,height:12,borderRadius:"50%",background:"#febc2e"}}),',
  '          h("div",{style:{width:12,height:12,borderRadius:"50%",background:"#28c840"}})',
  '        ),',
  '        h("div",{style:{marginLeft:12}},["\\u0424\\u0430\\u0439\\u043b","\\u041f\\u0440\\u0430\\u0432\\u043a\\u0430","\\u0412\\u0438\\u0434","\\u041f\\u0435\\u0440\\u0435\\u0445\\u043e\\u0434","\\u0417\\u0430\\u043f\\u0443\\u0441\\u043a","\\u0421\\u043f\\u0440\\u0430\\u0432\\u043a\\u0430"].map(function(m){return h("span",{key:m,style:{marginRight:12,cursor:"default"}},m);}))',
  '      ),',
  '      h("span",{style:{color:"#858585"}},"vscode-clone \\u2014 standalone"),',
  '      h("div",{style:{width:64}})',
  '    ),',
  '',
  '    h("div",{style:{display:"flex",flex:1,overflow:"hidden"}},',
  '',
  '      h("div",{style:{display:"flex",flexDirection:"column",justifyContent:"space-between",width:48,background:"#333",padding:"8px 0",flexShrink:0}},',
  '        h("div",{style:{display:"flex",flexDirection:"column",alignItems:"center",gap:4}},',
  '          [["files","\\ud83d\\udcc1","\\u041f\\u0440\\u043e\\u0432\\u043e\\u0434\\u043d\\u0438\\u043a"],["search","\\ud83d\\udd0d","\\u041f\\u043e\\u0438\\u0441\\u043a"],["debug","\\ud83d\\udc1b","\\u041e\\u0442\\u043b\\u0430\\u0434\\u043a\\u0430"],["ext","\\ud83e\\udde9","\\u0420\\u0430\\u0441\\u0448\\u0438\\u0440\\u0435\\u043d\\u0438\\u044f"]].map(function(item){var k=item[0],e=item[1],label=item[2];return h("button",{key:k,title:label,onClick:function(){setPanel(k);},style:{display:"flex",width:48,height:40,alignItems:"center",justifyContent:"center",background:"none",border:"none",cursor:"pointer",fontSize:20,opacity:panel===k?1:0.5,borderLeft:panel===k?"2px solid #fff":"2px solid transparent"}},e);})',
  '        ),',
  '        h("div",{style:{display:"flex",flexDirection:"column",alignItems:"center",gap:4}},',
  '          h("button",{style:{background:"none",border:"none",cursor:"pointer",fontSize:20,opacity:0.5,padding:8}},"\\ud83d\\udc64"),',
  '          h("button",{style:{background:"none",border:"none",cursor:"pointer",fontSize:20,opacity:0.5,padding:8}},"\\u2699\\ufe0f")',
  '        )',
  '      ),',
  '',
  '      h("div",{style:{display:"flex",flexDirection:"column",width:256,background:"#252526",flexShrink:0,overflow:"hidden"}},',
  '',
  '        panel==="files"&&h("div",{style:{display:"flex",flexDirection:"column",height:"100%",overflow:"hidden"}},',
  '          h("div",{style:{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"8px 16px",fontSize:11,fontWeight:700,textTransform:"uppercase",letterSpacing:1,color:"#bbb",flexShrink:0}},',
  '            h("span",null,"\\u041f\\u0440\\u043e\\u0432\\u043e\\u0434\\u043d\\u0438\\u043a"),',
  '            h("div",{style:{display:"flex",gap:8}},',
  '              h("button",{title:"New File",onClick:function(){createRoot("file");},style:{background:"none",border:"none",cursor:"pointer",color:"#858585",fontSize:16}},"+\\ud83d\\udcc4"),',
  '              h("button",{title:"New Folder",onClick:function(){createRoot("folder");},style:{background:"none",border:"none",cursor:"pointer",color:"#858585",fontSize:16}},"+\\ud83d\\udcc1")',
  '            )',
  '          ),',
  '          h("div",{style:{padding:"2px 16px 4px",fontSize:11,fontWeight:700,textTransform:"uppercase",color:"#ccc"}},"\\u041f\\u0420\\u041e\\u0415\\u041a\\u0422"),',
  '          h("div",{style:{flex:1,overflowY:"auto"}},',
  '            h(FileTree,{nodes:tree,activeId:activeId,onOpen:openFile,onToggle:toggleFolder,onRename:rename,onDelete:del,onCreate:create,renamingId:renamingId,setRenamingId:setRenaming})',
  '          )',
  '        ),',
  '',
  '        panel==="search"&&h("div",{style:{display:"flex",flexDirection:"column",height:"100%",overflow:"hidden"}},',
  '          h("div",{style:{padding:"8px 16px",fontSize:11,fontWeight:700,textTransform:"uppercase",color:"#bbb"}},"\\u041f\\u043e\\u0438\\u0441\\u043a"),',
  '          h("div",{style:{padding:"0 12px",display:"flex",flexDirection:"column",gap:8}},',
  '            h("input",{value:searchQ,onChange:function(e){setSearchQ(e.target.value);},placeholder:"\\u041d\\u0430\\u0439\\u0442\\u0438...",style:{width:"100%",background:"#3c3c3c",border:"none",color:"#ccc",padding:"6px 8px",fontSize:13,outline:"none",borderRadius:2}}),',
  '            h("div",{style:{display:"flex",gap:8}},',
  '              h("input",{value:replaceQ,onChange:function(e){setReplaceQ(e.target.value);},placeholder:"\\u0417\\u0430\\u043c\\u0435\\u043d\\u0438\\u0442\\u044c...",style:{flex:1,background:"#3c3c3c",border:"none",color:"#ccc",padding:"6px 8px",fontSize:13,outline:"none",borderRadius:2}}),',
  '              h("button",{onClick:replaceAll,style:{background:"#0e639c",border:"none",color:"#fff",padding:"4px 10px",cursor:"pointer",borderRadius:2,fontSize:12}},"\\u2192")',
  '            )',
  '          ),',
  '          searchQ&&h("div",{style:{padding:"4px 12px",fontSize:12,color:"#858585"}},searchResults.length+" \\u0441\\u043e\\u0432\\u043f\\u0430\\u0434\\u0435\\u043d\\u0438\\u0439"),',
  '          h("div",{style:{flex:1,overflowY:"auto",marginTop:4}},',
  '            searchResults.map(function(r,i){return h("div",{key:i,onClick:function(){openFile(r.node);},style:{padding:"4px 12px",cursor:"pointer",borderBottom:"1px solid #2a2a2a"},onMouseEnter:function(e){e.currentTarget.style.background="#2a2d2e";},onMouseLeave:function(e){e.currentTarget.style.background="transparent";}},',
  '              h("div",{style:{color:"#4ec9b0",fontSize:12}},r.node.name+":"+r.line),',
  '              h("div",{style:{color:"#858585",fontSize:12,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}},r.text)',
  '            );})',
  '          )',
  '        ),',
  '',
  '        panel==="debug"&&h("div",{style:{padding:12}},',
  '          h("div",{style:{fontSize:11,fontWeight:700,textTransform:"uppercase",color:"#bbb",marginBottom:8}},"\\u041e\\u0442\\u043b\\u0430\\u0434\\u043a\\u0430"),',
  '          h("button",{style:{display:"flex",alignItems:"center",justifyContent:"center",gap:8,width:"100%",padding:"6px",background:"#0e639c",border:"none",color:"#fff",cursor:"pointer",borderRadius:2,fontSize:13,marginBottom:12}},"\\u25b6 \\u0417\\u0430\\u043f\\u0443\\u0441\\u0442\\u0438\\u0442\\u044c \\u0438 \\u043e\\u0442\\u043b\\u0430\\u0434\\u0438\\u0442\\u044c"),',
  '          h("div",{style:{fontSize:11,fontWeight:700,textTransform:"uppercase",color:"#bbb",marginBottom:6}},"\\u0422\\u043e\\u0447\\u043a\\u0438 \\u043e\\u0441\\u0442\\u0430\\u043d\\u043e\\u0432\\u0430"),',
  '          [{f:"App.jsx",l:8},{f:"index.css",l:3}].map(function(b,i){return h("div",{key:i,style:{display:"flex",alignItems:"center",gap:8,padding:"4px 0",fontSize:13}},h("span",{style:{width:10,height:10,borderRadius:"50%",background:"#e51400",display:"inline-block"}}),h("span",null,b.f),h("span",{style:{color:"#858585"}},"\\u0441\\u0442\\u0440\\u043e\\u043a\\u0430 "+b.l));}),',
  '          h("div",{style:{fontSize:11,fontWeight:700,textTransform:"uppercase",color:"#bbb",margin:"12px 0 6px"}},"\\u0421\\u0442\\u0435\\u043a \\u0432\\u044b\\u0437\\u043e\\u0432\\u043e\\u0432"),',
  '          h("div",{style:{color:"#858585",fontSize:13}},"\\u041f\\u0440\\u043e\\u0433\\u0440\\u0430\\u043c\\u043c\\u0430 \\u043d\\u0435 \\u0437\\u0430\\u043f\\u0443\\u0449\\u0435\\u043d\\u0430")',
  '        ),',
  '',
  '        panel==="ext"&&h("div",{style:{display:"flex",flexDirection:"column",height:"100%",overflow:"hidden"}},',
  '          h("div",{style:{padding:"8px 16px",fontSize:11,fontWeight:700,textTransform:"uppercase",color:"#bbb"}},"\\u0420\\u0430\\u0441\\u0448\\u0438\\u0440\\u0435\\u043d\\u0438\\u044f"),',
  '          h("div",{style:{padding:"0 12px 8px"}},h("input",{placeholder:"\\u041f\\u043e\\u0438\\u0441\\u043a \\u0440\\u0430\\u0441\\u0448\\u0438\\u0440\\u0435\\u043d\\u0438\\u0439...",style:{width:"100%",background:"#3c3c3c",border:"none",color:"#ccc",padding:"6px 8px",fontSize:13,outline:"none",borderRadius:2}})),',
  '          h("div",{style:{flex:1,overflowY:"auto"}},EXT.map(function(ext,i){return h("div",{key:i,style:{display:"flex",gap:12,padding:"8px 12px",borderBottom:"1px solid #2a2a2a"}},h("div",{style:{width:36,height:36,background:"#0e639c",borderRadius:4,display:"flex",alignItems:"center",justifyContent:"center",fontSize:20,flexShrink:0}},"\\ud83d\\udd0c"),h("div",{style:{flex:1,minWidth:0}},h("div",{style:{fontSize:13,fontWeight:600,color:"#fff"}},ext.name),h("div",{style:{fontSize:12,color:"#858585",overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}},ext.desc),h("button",{onClick:function(){toggleExt(ext.name);},style:{marginTop:4,padding:"2px 8px",fontSize:11,background:inst.has(ext.name)?"#3c3c3c":"#0e639c",border:"none",color:inst.has(ext.name)?"#ccc":"#fff",cursor:"pointer",borderRadius:2}},inst.has(ext.name)?"\\u0423\\u0434\\u0430\\u043b\\u0438\\u0442\\u044c":"\\u0423\\u0441\\u0442\\u0430\\u043d\\u043e\\u0432\\u0438\\u0442\\u044c")));}))',
  '        )',
  '      ),',
  '',
  '      h("div",{style:{display:"flex",flexDirection:"column",flex:1,overflow:"hidden"}},',
  '',
  '        h("div",{style:{display:"flex",height:36,background:"#252526",flexShrink:0,overflowX:"auto"}},',
  '          tabs.map(function(tab){return h("div",{key:tab.id,onClick:function(){setActiveId(tab.id);},',
  '            style:{display:"flex",alignItems:"center",gap:8,padding:"0 12px",cursor:"pointer",fontSize:13,position:"relative",flexShrink:0,borderRight:"1px solid #1e1e1e",background:activeId===tab.id?"#1e1e1e":"#2d2d2d",color:activeId===tab.id?"#fff":"#969696"}},',
  '            activeId===tab.id&&h("div",{style:{position:"absolute",top:0,left:0,right:0,height:1,background:"#007acc"}}),',
  '            h("span",{style:{fontSize:14}},fileEmoji(tab.name)),',
  '            h("span",null,tab.name),',
  '            dirty.has(tab.id)',
  '              ?h("span",{onClick:function(e){closeTab(tab.id,e);},style:{width:8,height:8,borderRadius:"50%",background:"#ccc",flexShrink:0}})',
  '              :h("button",{onClick:function(e){closeTab(tab.id,e);},style:{background:"none",border:"none",color:"#969696",cursor:"pointer",padding:"0 2px",fontSize:16,lineHeight:1}},"\\u00d7")',
  '          );})',
  '        ),',
  '',
  '        activeNode&&h("div",{style:{display:"flex",alignItems:"center",gap:6,height:24,background:"#1e1e1e",padding:"0 16px",fontSize:12,color:"#858585",flexShrink:0}},',
  '          h("span",null,"\\ud83d\\udcc1 \\u043f\\u0440\\u043e\\u0435\\u043a\\u0442"),h("span",null,"\\u203a"),h("span",{style:{color:"#ccc"}},activeNode.name),',
  '          h("button",{onClick:save,style:{marginLeft:"auto",background:"none",border:"none",color:dirty.has(activeNode.id)?"#ccc":"#555",cursor:"pointer",fontSize:12}},dirty.has(activeNode.id)?"\\u25cf \\u0421\\u043e\\u0445\\u0440\\u0430\\u043d\\u0438\\u0442\\u044c":"\\u2713 \\u0421\\u043e\\u0445\\u0440\\u0430\\u043d\\u0435\\u043d\\u043e")',
  '        ),',
  '',
  '        h("div",{style:{display:"flex",flex:1,overflow:"hidden"}},',
  '          activeNode',
  '            ?h(CodeEditor,{key:activeNode.id,value:activeNode.content||"",lang:lang,onChange:setContent})',
  '            :h("div",{style:{display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",flex:1,color:"#555",gap:12}},',
  '              h("div",{style:{fontSize:80}},"\\ud83d\\udcdd"),',
  '              h("div",{style:{fontSize:18}},"\\u0412\\u044b\\u0431\\u0435\\u0440\\u0438\\u0442\\u0435 \\u0444\\u0430\\u0439\\u043b \\u0434\\u043b\\u044f \\u0440\\u0435\\u0434\\u0430\\u043a\\u0442\\u0438\\u0440\\u043e\\u0432\\u0430\\u043d\\u0438\\u044f"),',
  '              h("div",{style:{fontSize:13,color:"#444"}},"\\u041e\\u0442\\u043a\\u0440\\u043e\\u0439\\u0442\\u0435 \\u043f\\u0440\\u043e\\u0432\\u043e\\u0434\\u043d\\u0438\\u043a \\u0441\\u043b\\u0435\\u0432\\u0430")',
  '            )',
  '        ),',
  '',
  '        showTerm&&h("div",{style:{display:"flex",flexDirection:"column",height:208,borderTop:"1px solid #333",flexShrink:0}},',
  '          h("div",{style:{display:"flex",alignItems:"center",height:32,background:"#181818",padding:"0 12px",fontSize:11,textTransform:"uppercase",gap:16,flexShrink:0}},',
  '            h("span",{style:{color:"#fff",borderBottom:"2px solid #007acc",paddingBottom:2}},"\\u0422\\u0435\\u0440\\u043c\\u0438\\u043d\\u0430\\u043b"),',
  '            h("span",{style:{color:"#858585",cursor:"pointer"}},"\\u041f\\u0440\\u043e\\u0431\\u043b\\u0435\\u043c\\u044b"),',
  '            h("span",{style:{color:"#858585",cursor:"pointer"}},"\\u0412\\u044b\\u0432\\u043e\\u0434"),',
  '            h("button",{onClick:function(){setShowTerm(false);},style:{marginLeft:"auto",background:"none",border:"none",color:"#858585",cursor:"pointer",fontSize:18}},"\\u00d7")',
  '          ),',
  '          h("div",{style:{flex:1,overflow:"hidden"}},h(Terminal))',
  '        )',
  '      )',
  '    ),',
  '',
  '    h("div",{style:{display:"flex",alignItems:"center",justifyContent:"space-between",height:24,background:"#007acc",padding:"0 12px",fontSize:12,color:"#fff",flexShrink:0}},',
  '      h("div",{style:{display:"flex",gap:12}},',
  '        h("span",null,"\\ud83c\udf3f main"),',
  '        h("span",null,"\\u2717 0  \\u26a0 0")',
  '      ),',
  '      h("div",{style:{display:"flex",gap:12}},',
  '        h("button",{onClick:function(){setShowTerm(function(s){return !s;});},style:{background:"none",border:"none",color:"#fff",cursor:"pointer",fontSize:12}},"\\u2328 \\u0422\\u0435\\u0440\\u043c\\u0438\\u043d\\u0430\\u043b"),',
  '        h("span",null,"\\u0421\\u0442\\u0440\\u043e\\u043a: "+(activeNode&&activeNode.content?activeNode.content.split("\\n").length:0)),',
  '        h("span",null,(lang||"text").toUpperCase()),',
  '        h("span",null,"UTF-8"),',
  '        h("span",null,"\\u041f\\u0440\\u043e\\u0431\\u0435\\u043b\\u044b: 2")',
  '      )',
  '    )',
  '  );',
  '}',
  '',
  'ReactDOM.createRoot(document.getElementById("root")).render(h(IDE));',
];

const FOOTER = [
  '</script>',
  '</body>',
  '</html>',
].join('\n');

// Собираем полный HTML
export const VSCODE_HTML: string = HEAD + '\n' + LOGIC.join('\n') + '\n' + FOOTER;